CREATE USER VEM_SER IDENTIFIED BY oracle;

GRANT CONNECT TO VEM_SER;

GRANT CONNECT, RESOURCE, DBA TO VEM_SER;

GRANT CREATE SESSION TO VEM_SER;

GRANT DBA TO VEM_SER;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO VEM_SER;

GRANT UNLIMITED TABLESPACE TO VEM_SER;
GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
GRANT CREATE TABLE TO VEM_SER;
GRANT GLOBAL QUERY REWRITE TO VEM_SER;
GRANT SELECT ANY TABLE TO VEM_SER;

CREATE TABLE PESSOA (
    id_pessoa NUMBER NOT NULL,
    txt_nome VARCHAR2(2055) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR2(14), -- +5551995249346
    idade NUMBER(3) NOT NULL,
    altura DECIMAL(4,2) NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    PRIMARY KEY(id_pessoa)
);


CREATE SEQUENCE VEM_SER.SEQ_PESSOA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

--
INSERT INTO VEM_SER.PESSOA (ID_PESSOA, NOME, DATA_NASCIMENTO, CPF, email) VALUES 
(seq_pessoa.nextval, 'Jeff', TO_DATE('03-08-2002', 'dd-mm-yyyy'), '1351001500', 'pedro.arruda@dbccompany.com.br') ;

--
UPDATE VEM_SER.PESSOA 
   SET EMAIL = 'pedroarruda8@live.com'
 WHERE ID_PESSOA = 1

--
SELECT -- COUNT(*) AS qtd_pessoas
     --, 'aaa' ||'-'|| 'bbb'
       TO_CHAR(DATA_NASCIMENTO,'dd/mm/yyyy HH24:mm:ss') 
  FROM PESSOA
;  