version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: bd-postgres16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pedrovemser
      POSTGRES_PASSWORD: pedro
      POSTGRES_DB: "vs14-back"
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
